# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Coding/Vivado/cache/cache.srcs/sources_1/ip/cpu_to_cache_fifo/cpu_to_cache_fifo.xci
# IP: The module: 'cpu_to_cache_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Coding/Vivado/cache/cache.gen/sources_1/ip/cpu_to_cache_fifo/cpu_to_cache_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_to_cache_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Coding/Vivado/cache/cache.gen/sources_1/ip/cpu_to_cache_fifo/cpu_to_cache_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_to_cache_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Coding/Vivado/cache/cache.gen/sources_1/ip/cpu_to_cache_fifo/cpu_to_cache_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_to_cache_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Coding/Vivado/cache/cache.srcs/sources_1/ip/cpu_to_cache_fifo/cpu_to_cache_fifo.xci
# IP: The module: 'cpu_to_cache_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Coding/Vivado/cache/cache.gen/sources_1/ip/cpu_to_cache_fifo/cpu_to_cache_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_to_cache_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Coding/Vivado/cache/cache.gen/sources_1/ip/cpu_to_cache_fifo/cpu_to_cache_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_to_cache_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Coding/Vivado/cache/cache.gen/sources_1/ip/cpu_to_cache_fifo/cpu_to_cache_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_to_cache_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
